### PR TITLE
Use topkg

### PR DESCRIPTION
**Pull request by samoht**
- switch to topkg
- remove camlp4
- split into multiple opam packages

| opam packages | ocamlfind libraries |
| --- | --- |
| mirage-console-unix | mirage-console-unix |
| mirage-console-xen | mirage-console-xen |
| mirage-console-backend | mirage-console-backend |
| mirage-console-proto | mirage-console-proto |
| mirage-console-cli | mirage-console-cli |

### CODE REVIEW

**Comment by samoht** [comment]
/cc @dbuenzli

@avsm are you ok with the removal of depopts and the split into multiple opam packages? I think it puts less magic in the build system and make it easier to understand which depopts is used for what.

**Comment by avsm** [comment]
* mirage-console-proto needs to become mirage-console-xen-proto
* mirage-console-backend needs to become mirage-console-xen-backend
* mirage-console-cli needs to be become mirage-console-xen-cli

See also djwillia/solo5#36 for other mirage-console solo5 libraries that are incoming with a similar split, but in a different repo -- this needs to be topkg'ed up as well but I can do that.

**Comment by hannesm** [comment]
can we move forward with this @samoht ? the parts I'm mostly in favour of are getting rid of camlp4 and moving to topkg... @avsm seems to want some more renaming

**Comment by samoht** [comment]
I've rebased my initial PR, I have renamed the libraries as @avsm requested, e.g:

| opam packages | ocamlfind libraries |
| --- | --- |
| mirage-console-unix | mirage-console-unix |
| mirage-console-xen | mirage-console-xen |
| mirage-console-xen-backend | mirage-console-xen-backend |
| mirage-console-xen-proto | mirage-console-xen-proto |
| mirage-console-xen-cli | mirage-console-xen-cli |

**Comment by samoht** [comment]
@hannesm All green again!

**Comment by hannesm** [comment]
thanks!  I suspect we'll need to get the new packages into mirage-dev repo (I wouldn't invest time to backport this to Mirage2 (and cut releases), but rather work on an imminent Mirage3 release)

**Pull request merged**
